# Generated by Django 3.2 on 2021-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=30)),
                ('msg', models.TextField(default='', max_length=150)),
            ],
        ),
    ]
